DROP TABLE IF EXISTS t_olcs;
CREATE TABLE t_olcs
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_user CHAR(36) NOT NULL COMMENT '用户',
  c_replier CHAR(36) DEFAULT NULL COMMENT '客服',
  c_genre VARCHAR(255) DEFAULT NULL COMMENT '类型',
  c_content TEXT DEFAULT NULL COMMENT '内容',
  c_time DATETIME NOT NULL COMMENT '时间',

  PRIMARY KEY pk(c_id) USING HASH,
  KEY k_user_time(c_user,c_time) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;