DROP TABLE IF EXISTS t_faq;
CREATE TABLE t_faq
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_key VARCHAR(255) NOT NULL COMMENT '引用KEY',
  c_sort INT DEFAULT 0 COMMENT '顺序',
  c_subject VARCHAR(255) DEFAULT NULL COMMENT '标题',
  c_content TEXT DEFAULT NULL COMMENT '内容',
  c_read INT DEFAULT 0 COMMENT '阅读数',

  PRIMARY KEY pk(c_id) USING HASH,
  KEY k_key(c_key) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;