DROP TABLE IF EXISTS t_device;
CREATE TABLE t_device
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_user CHAR(36) NOT NULL COMMENT '用户',
  c_sid VARCHAR(255) NOT NULL COMMENT 'Session ID',
  c_type VARCHAR(255) DEFAULT NULL COMMENT '类型',
  c_identifier VARCHAR(255) DEFAULT NULL COMMENT '标识符',
  c_lang VARCHAR(255) DEFAULT NULL COMMENT '语言',
  c_time DATETIME DEFAULT NULL COMMENT '时间',

  PRIMARY KEY pk(c_id) USING HASH,
  KEY k_user(c_user) USING HASH,
  UNIQUE KEY uk_sid(c_sid) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;