DROP TABLE IF EXISTS t_upgrader;
CREATE TABLE t_upgrader
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_version INT DEFAULT 0 COMMENT '版本号',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '版本名',
  c_forced INT DEFAULT 0 COMMENT '强制升级：0-否；1-是',
  c_explain TEXT DEFAULT NULL COMMENT '说明',
  c_android VARCHAR(255) DEFAULT NULL COMMENT 'Android升级URL',
  c_ios VARCHAR(255) DEFAULT NULL COMMENT 'iOS升级URL',
  c_windows VARCHAR(255) DEFAULT NULL COMMENT 'Windows升级URL',
  c_macos VARCHAR(255) DEFAULT NULL COMMENT 'MacOS升级URL',
  c_linux VARCHAR(255) DEFAULT NULL COMMENT 'Linux升级URL',
  c_file TEXT DEFAULT NULL COMMENT '升级包',

  PRIMARY KEY pk(c_id) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
