DROP TABLE IF EXISTS t_keyvalue;
CREATE TABLE t_keyvalue
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_key VARCHAR(255) NOT NULL COMMENT '键',
  c_value VARCHAR(10240) DEFAULT NULL COMMENT '值',

  PRIMARY KEY pk(c_id) USING HASH,
  UNIQUE KEY uk_key(c_key) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS m_keyvalue;
CREATE TABLE m_keyvalue
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_key VARCHAR(255) NOT NULL COMMENT '键',
  c_value VARCHAR(10240) DEFAULT NULL COMMENT '值',

  PRIMARY KEY pk(c_id) USING HASH,
  UNIQUE KEY uk_key(c_key) USING BTREE
) ENGINE=Memory DEFAULT CHARSET=utf8mb4;
