DROP TABLE IF EXISTS t_notification;
CREATE TABLE t_notification
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_user CHAR(36) NOT NULL COMMENT '用户',
  c_genre VARCHAR(255) DEFAULT NULL COMMENT '类型',
  c_subject VARCHAR(255) DEFAULT NULL COMMENT '内容',
  c_content TEXT DEFAULT NULL COMMENT '内容',
  c_expiration DATETIME DEFAULT NULL COMMENT '过期时间',
  c_time DATETIME DEFAULT NULL COMMENT '发布时间',
  c_read DATETIME DEFAULT NULL COMMENT '阅读时间',

  PRIMARY KEY pk(c_id) USING HASH,
  KEY k_user_time(c_user,c_time) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;