DROP TABLE IF EXISTS t_channel;
CREATE TABLE t_channel
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_sort INT DEFAULT 0 COMMENT '顺序',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '名称',
  c_icon VARCHAR(255) DEFAULT NULL COMMENT '图标',
  c_qrcode VARCHAR(255) DEFAULT NULL COMMENT '二维码',
  c_min INT DEFAULT 0 COMMENT '最小金额',
  c_max INT DEFAULT 0 COMMENT '最大金额',

  PRIMARY KEY pk(c_id) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;