DROP TABLE IF EXISTS t_rate;
CREATE TABLE t_rate
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_game CHAR(36) NOT NULL COMMENT '游戏',
  c_type VARCHAR(255) DEFAULT NULL COMMENT '类型',
  c_sort INT DEFAULT 0 COMMENT '顺序',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '名称',
  c_amount INT DEFAULT 0 COMMENT '赔率',
  c_max INT DEFAULT 0 COMMENT '封顶',
  c_param VARCHAR(255) DEFAULT NULL COMMENT '特殊',
  c_memo VARCHAR(255) DEFAULT NULL COMMENT '备注',

  PRIMARY KEY pk(c_id) USING HASH,
  KEY k_game(c_game) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;